name: Module Test
on: [push]
jobs:
  test-module-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - run: uname -a
      - run: ls -hal
      - run: sudo apt install gcc g++ linux-headers-$(uname -r)
      - run: make && cd module && make
      - run: sudo insmod module/sample.ko
      - run: ./example
